steps:
# Dockerイメージをビルドするステップ
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/grpc-chat-server', '.']

# ビルドしたイメージをGCRにプッシュするステップ
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/grpc-chat-server']

# Cloud Runにデプロイするステップ
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'grpc-chat-server', '--image', 'gcr.io/$PROJECT_ID/grpc-chat-server', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
